// src/components/react/Counter.tsx
import { useState } from "react";
import Button from "./Button";

const Counter = () => {
  const [count, setCount] = useState(0);
  console.log(`React rendering`);
  return (
    <div className="flex flex-row gap-6 items-center">
      <Button label="-" onClick={() => setCount(count - 1)} />
      <div className="w-12 text-center">{count}</div>
      <Button label="+" onClick={() => setCount(count + 1)} />
    </div>
  );
};

export default Counter;

// src/components/svelte/Counter.svelte

<script>
    import Button from "./Button.svelte";
	let count = 0;
    console.log(`Svelte rendering`);
</script>

<div class="flex flex-row gap-6 items-center">
    <Button label="-" onClick={() => count -= 1}  />
        <div class="w-12 text-center">{ count }</div>
    <Button label="+" onClick={() => count += 1}  />
</div>
