// src/components/react/Counter.tsx
import { useState } from "react";
import Button from "./Button";

const Counter = () => {
  const [count, setCount] = useState(0);
  return (
    <div className="flex flex-row gap-6 items-center">
      <Button label="-" onClick={() => setCount(count - 1)} />
      <div className="w-12 text-center">{count}</div>
      <Button label="+" onClick={() => setCount(count + 1)} />
    </div>
  );
};

export default Counter;

// src/components/vue/Counter.vue
<script setup lang="ts">
import { ref } from "vue";
import Button from "./Button.vue";
const count = ref(0);
</script>

<template>
  <div class="flex flex-row gap-6 items-center">
    <Button label="-" @click="count--" />
    <div class="w-12 text-center">{{ count }}</div>
    <Button label="+" @click="count++" />
  </div>
</template>
