// src/components/vue/StateCounter.vue
<script setup lang="ts">
import { useStore } from "@nanostores/vue";
import Button from "./Button.vue";
import { counter } from "../../counterStore";

const $counter = useStore(counter);
</script>

<template>
  <div class="flex flex-row gap-6 items-center">
    <Button label="-" @click="counter.set($counter - 1)" />
    <div class="w-12 text-center">{{ $counter }}</div>
    <Button label="+" @click="counter.set($counter + 1)" />
  </div>
</template>

// src/components/react/StateCounter.tsx
import { useStore } from "@nanostores/react";
import { counter } from "../../counterStore";
import Button from "./Button";

const StateCounter = () => {
  const $counter = useStore(counter);
  return (
    <div className="flex flex-row gap-6 items-center">
      <Button label="-" onClick={() => counter.set($counter - 1)} />
      <div className="w-12 text-center">{$counter}</div>
      <Button label="+" onClick={() => counter.set($counter + 1)} />
    </div>
  );
};

export default StateCounter;
